on:
  push:
    branches:
      - main

name: 🚀 Deploy website
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install node modules
        run: yarn

      - run: yarn build
      - name: Sync
        uses: omppye-lab/gcp-storage-sync@master
        with:
          args: -d
        env:
          GCP_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.GOOGLE_CREDENTIALS }}
          GCP_STORAGE_BUCKET: geforcy.com
          SOURCE_DIR: ./dist
